### PR TITLE
Fixed detecting of Code Set (CODE128)

### PR DESCRIPTION
**Pull request by SanichKotikov**

### CODE REVIEW

**Comment by lindell** [comment]
Nice! It was not right before, but is it 100% correct now?

Is it not better to do:
````javascript
cLength >= 4 || (cLength == 2 && string.length == 2)
````

**Comment by lindell** [comment]
And was it that broken before? It would encode 123 digits as.
`[STARTC]` `12` `[CHANGETO A/B]` `1`

Which is 3 characters. The same as.
`[START A/B]` `1` `2` `3`

**Comment by SanichKotikov** [comment]
Not sure about `"12"`. Some soft encode it as C, but others as B. I'll try to find any information about this case.

For example, `"12abc"` was broken. It starts as C but should as B.

**Comment by lindell** [comment]
I think `[START A/B]` `1` `2` `a` `b` `c` is nicer and think it is worthy of merge.
But please explain why `[STARTC]` `12` `[CHANGETO A/B]` `a` `b` `c` is wrong.

Others might do it differently, but it is not breaking any specs or does encode it with more data than needed right?

**Comment by SanichKotikov** [comment]
Looks like there is no any sources of truth. All soft that I checked doing it in different ways. Maybe we should close this pr then.

**Pull request closed without merging**
