### PR TITLE
Codabar switch B & C

### PR DESCRIPTION
**Pull request by edward9145**
After used some bar scanner apps to test the Codabar which gen by this lib, 
I found that the B and C are misencoded.

Codabar wiki:
https://en.wikipedia.org/wiki/Codabar

### CODE REVIEW

**Comment by edward9145** [comment]
Here is an example "B0C" which generated by another barcode generator.

https://racoindustries.com/barcodegenerator/1d/codabar/
createbarcode

JsBarcode
b0c

```javascript
JsBarcode("#barcode", "B0C", {
        format: "codabar",
        width: 4,
        height: 50,
        displayValue: false
      });
```

**Comment by edward9145** [comment]
#209 reported the sample problem

**Comment by SanichKotikov** [comment]
Hi, thanks for your pr. I'll try to investigate the issue. But I'm not sure I can do it soon... the end of a year.

**Comment by SanichKotikov** [comment]
Tested in several different generators and I can confirm that this is a valid changes. @edward9145 great job, txh! @lindell I suppose we should merge it, what do you think?

**Comment by lindell** [comment]
Does indeed look good. 

Thank you very much for for

**Pull request merged**
