### PR TITLE
Refactor EAN

### PR DESCRIPTION
**Pull request by SanichKotikov**
I tried to make the code more readable and clean.

### CODE REVIEW

**Comment by SanichKotikov** [comment]
Looks like we have a problem with `publish-release` module in CI

**Comment by SanichKotikov** [comment]
@lindell hi. Any comments/suggestions?

**Comment by lindell** [comment]
Sorry, I've been a little open source burned out lately. I'm currently on vacation but will try to take care of things once I'm home (and not jetlagged) in a couple of days

**Comment by lindell** [comment]
I will take a look at what made travis fail

**Comment by lindell** [comment]
Created a PR in publish-release to fix the issue. If it is not merged soon we can revert to an older version.

https://github.com/remixz/publish-release/pull/35

**Comment by lindell** [comment]
But feel free to merge this branch whenever you want 😄

**Pull request merged**
