### PR TITLE
Allow definition of space between barcode and text

### PR DESCRIPTION
**Pull request by fschaeffer**

### CODE REVIEW

**Comment by lindell** [comment]
Have you tested this code? I can see on the diffs that there is no way this is going to work.

**Comment by lindell** [comment]
Did test the code now, as expected the code does throw exception and does not generate barcodes any more.

**Comment by lindell** [comment]
Did an implementation of this that does work now b543a1cab3622c8c8f72a42e82f83d41ab5f4094

**Comment by fschaeffer** [comment]
Actually it worked locally but thanks that you found that error and fixed it.

**Pull request closed without merging**
