### PR TITLE
Refactor ITF

### PR DESCRIPTION
**Pull request by SanichKotikov**

### CODE REVIEW

**Comment by SanichKotikov** [comment]
Thx. Also, updated `barcode-building.json` just now.

**Comment by lindell** [comment]
Things does then also have to be updated in the readme and in the gh-pages branch since the ITF14 file is now removed

https://github.com/lindell/JsBarcode/blob/gh-pages/index.html#L210

**Comment by SanichKotikov** [comment]
@lindell I updated Readme & gh-pages https://github.com/lindell/JsBarcode/pull/238

**Comment by lindell** [comment]
Merge whenever :)

**Pull request merged**
