### PR TITLE
Fixed/updated dependencies + replaced merge function

### PR DESCRIPTION
**Pull request by SanichKotikov**
Main idea of this PR is fixed/updated dependencies' versions. Sometimes it's a pain when one developer have one versions of dependencies, but others have other versions. Fixed versions also guarantees that code runs in the same environment on test server, for example.

Also I've updated babel preset and used _Object Spread Properties_ as example.

### CODE REVIEW

**Comment by lindell** [comment]
I'm 100% with you on setting dependencies to fixed versions for a project, as this may cause problems is production for people.

This thing is that this project does not have any dependencies to run. Only devDependencies to be able to develop the code. My idea is that it is better for these to not be fixed since this can guarantee development with the latest (non-major releases) and that the implications if someone, one time will have a problem with getting started is not that great.

Thoughts?

**Comment by lindell** [comment]
I could absolutely merge in the `experimentalObjectRestSpread` if there is any reason for it.

But I've actually been thinking about removing the merge function all together since `Object.assign` does the same thing

**Comment by SanichKotikov** [comment]
Sometimes, even dev dependencies can break something and then it's a "nice" time to solve a quest named "try to find the problem". I had this problem in several past projects, so I just want to prevent it :)

`ObjectRestSpread` makes your code clean, as for me, and thanks to Babel it transforms to `Object.assign` with a fallback, because `Object.assign` has not so good support.

**Comment by SanichKotikov** [comment]
One more case. Time by time I pull libraries, and when I try to compile, some of them doesn't work because of unfixed dependencies.

**Comment by SanichKotikov** [comment]
@lindell any thoughts?

**Comment by lindell** [comment]
I've been away for some days and have not been able to answer.

The merge thing is definitely something I want to merge but I'm still not sure on the dependencies.
I started to look at bigger repos and they seems to not lock the devDependecies. For example [React](https://github.com/facebook/react/blob/master/package.json), [Vue](https://github.com/vuejs/vue/blob/dev/package.json) and [bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/package.json) does not lock to specific versions.

**Comment by SanichKotikov** [comment]
React and Vue have `yarn.lock` and looks like they don't really care how `npm` works :) Ok, maybe it makes sense do not fix versions for an open source project. If you want I can create a separate PR with same changes but without fixing dev versions. Also I can add this ESLint rule http://eslint.org/docs/rules/curly that can help to avoid lint problem in future. What do you thing?

**Comment by lindell** [comment]
Sounds like a good idea :)

**Pull request closed without merging**
