### PR TITLE
Non-Flat Style EAN-8 Barcode Implemented.

### PR DESCRIPTION
**Pull request by saaiful**
check the issue https://github.com/lindell/JsBarcode/issues/164
Set `flat` value true/false in option, EAN-13 has this option

### CODE REVIEW

**Comment by lindell** [comment]
Hi and thanks for the PR :)

There are some minor problems with it thou. I am very strict with not breaking SOLID which you do here by changing the main library for things that are barcode specific. Currently there is no good way to add these options in the library but I have been thinking about making this change for a while. I will try to fix it this week.

**Comment by saaiful** [comment]
Thanks for creating this awesome project. I included the modified code in my application, this is your project do as you wish :)

<3 JsBarcode

**Comment by SanichKotikov** [comment]
Hi. I suppose it should looks like some helper or base class for EAN8/13.

**Comment by SanichKotikov** [comment]
Looks like we have to close this pr.
Anyway, I'll try to implement non-flat EAN8 as soon as I have some time.

**Pull request closed without merging**
